### ISSUE TITLE
Paper cuts in YAML serialization API

### ISSUE THREAD

**Issue by ischoegl** [Cantera/cantera#1053]
**Problem description**

After the introduction of new YAML features (especially in Python), there has been some discussion of minor 'paper cuts'. Below is a list of issues that could/should be addressed:

* [x] Unpythonic method names `Reaction.fromYaml`, `Reaction.listFromFile`, `Reaction.listFromYaml` ... *fix proposed in #1061* (now merged)
* [x] Similar for `Species.fromYaml`, etc. … *fix proposed in #1129* (now merged)
* [x] Per comment in #1031, it would be nice to have `Solution.write_yaml` be able to write into a string … *added to #692* (now merged)
* [x] ~It would be nice to have constructors that use keyword names that correspond to YAML field names. This is somewhat complicated by the occurrence of hyphens in many top-level fields (e.g. `rate-constant` for reaction definitions, see #995);~ an alternative `@classmethod` `from_dict` is an approach that does not have this limitation.
* [ ] With the introduction of `dict_to_anymap` in #1014, it is now possible to pass dictionaries that are equivalent to YAML definitions to the Python API. In #995, a new `Reaction.from_dict` is proposed (now merged). The same is possible for various other imports. ... *fix proposed in #1179*
* [x] ~With #984, the `input_data` field was introduced, which corresponds to the dictionary that can be used by `from_dict`. A consistent naming scheme may be beneficial, especially as the field does not preserve the original parameterization (see #1031).~ ... probably not an issue
* [x] ~It would be nice to allow for mixed `dict`/YAML string imports for `dict_to_anymap` (see #995).~ ... *implementation proposed in #1179*, but dropped 
* [x] ~At this point, YAML may refer to a file, string, or even a corresponding Python dictionary, where the context isn't always clear.~  ... probably not an issue
* [x] Root level information of the YAML parameterization is not accessible, see also #1013 … *fix proposed in #1129* (now merged)
* [ ] Per comments in #1031 and #984, there is some inconsistency of C++ definitions for `input`, which either refers to a member variable or a class method. As this was initially introduced in #584 (and/or related PR's), this part of the API is already released in 2.5.1 and thus is difficult to address. ... *not sure that this should be addressed*
* [x] There are some imperfections for YAML emitted output, see #1128 … *fixed in #1133*

**Additional context**

Some of the unpythonic method names are based on historic equivalents for XML and CTI. As those are to be deprecated, a renaming of legacy methods appears to be unwarranted.
